/* ========================================================================== */
/*	PROGRAM Price Stock Machine
    AUTHOR: Yuri Khechoyan & Jessie Wilkins
    COURSE NUMBER: CIS 210
    COURSE SECTION NUMBER: 01
    INSTRUCTOR NAME: Dr. Tian
    PROJECT NUMBER: 6
    DUE DATE: 9/29/2016
    
SUMMARY
	This program is designed to simulate Stock activity for 30 days
	Program will randomly generate changes (-10% to 10% positive & negative changes)
	Program will ask user to input: stock name, symbol, & current price
	When input is received, program will randomly generate next price of stock for
	the next 29 days (30 days total)
	
	Program will output to user:
	 	1. Stock Name 
	 	2. Stock Symbol  
	 	3. Yesterday's Price**** (user 'currentPrice' input)
	 	4. Today's Price (Randomly generated by Method)
	 	5. Price Movement (Today's Price - Yesterday's Price = +/- change)
	 	6. Change Percent (How to Calculate this?)
	 	
	 	**** = Next Day's (day 2, 3, 4, etc) Price is equal to Yesterday's 'Today Price'
	
INPUT
	Input from user will consist of Strings and Doubles
	Strings: Stock Name & Stock Symbol
	Doubles: Current Stock Price

OUTPUT
	Output from program will be shown on console similar to example format:
	
	STOCK      SYMBOL  YESTERDAY_PRICE 	TODAY_PRICE 	PRICE_MOVEMENT 		CHANGE_PERCENT 
Microsoft     	MSFT        45.65       	47.48           1.83            	4.00% 
 
Microsoft  		MSFT        47.48       	52.22           4.75                10.00% 
 
Microsoft  		MSFT        52.22       	49.61           -2.61               -5.00% 
 


ASSUMPTIONS
- None
*/

import java.util.Scanner;									//This imports the Scanner class used for input

public class PriceStockSimulation {
	public static void main(String[] args){
		//Variables
		String companyName = new String();					//companyName variable: new String Method
		String companySymbol = new String();				//companySymbol variable: new String Method
		double currentPrice = 0;							//currentPrice set to 0: before user input
		double nextPrice = 0;								//nextPrice set to 0: before user input
		double percentChange = 0;							//percentChange set to 0: before user input
		final int NUMBER_OF_DAYS = 30;						//NUMBER_OF_DAYS set to 30: constant used as limit for the for loop
				
		Scanner compNameInput = new Scanner(System.in);		//This creates an object for the company name input
		Scanner compSymbolInput = new Scanner(System.in);	//This creates an object for the company symbol input
		Scanner currentPriceInput = new Scanner(System.in);	//This creates an object for the current price input
		
		//Creates new Object of Stock for user input (different from default)
		Stock object = new Stock();
		
		//*******************************
		//		START OF PROGRAM		*
		//*******************************
		
		//This prints out the condition for using default values
		System.out.print("If the user enters NONE, NA, and 0.0 for the name of the company, the symbol, and yesterday's price ");
		System.out.println("respectively, it will use default values.");
		
		//This prints out the command to enter the name of the stock
		System.out.print("Please enter the name of the stock: ");
		
		//User enters the company name
		companyName = compNameInput.nextLine();
		
		//This prints out the command to enter the symbol of the stock
		System.out.print("Please enter the symbol of the stock: ");
		
		//User enters the company symbol
		companySymbol = compSymbolInput.nextLine();
		
		//This prints out the command to enter yesterday's price
		System.out.print("Please enter yesterday's price: ");
		
		//User enters the current price 
		currentPrice = currentPriceInput.nextDouble();
		
		//This determines if the default values should be used
		object.WhichDefaultValue(companyName, companySymbol, currentPrice);
		
		//This sets the next price
		object.priceChange();
		
		//This assigns the company name to the variable
		companyName = object.getName();
		
		//This assigns the company symbol to the variable
		companySymbol = object.getSymbol();
		
		//This assigns the current price to the variable
		currentPrice = object.getCurrentPrice();
		
		//This assigns the current price to the variable
		nextPrice = object.getNextPrice();
		
		//This assigns the next price to the variable
		percentChange = object.getPercentage();
		
		//This prints the category headers for each column
		object.printHeaders();
		
		//This starts the for loop that iterates for 30 times
		for(int i=1; i<=NUMBER_OF_DAYS; i++) {
			//This prints out the stock description
			object.printResults(companyName, companySymbol, currentPrice, nextPrice, percentChange);
			
			//This sets the current price to the value of the next price
			object.setCurrentPrice(nextPrice);
			
			//This changes the price of the next price
			object.priceChange();
			
			//This assigns the current price to the variable
			currentPrice = object.getCurrentPrice();
			
			//This assigns the next price to the variable
			nextPrice = object.getNextPrice();
			
			//This assigns the percentage to the variable
			percentChange = object.getPercentage();
		}//Closes 'for' loop
				
		//This closes the input objects
		compNameInput.close();								//This closes input object of the company name input
		compSymbolInput.close();							//This closes input object of the company symbol input
		currentPriceInput.close();							//This closes input object of the current price input
		
	}//Closes Main Method
}//Closes PriceStockSimulation Class
