/* ========================================================================== */
/*	PROGRAM Price Stock Machine
    AUTHOR: Yuri Khechoyan & Jessie Wilkins
    COURSE NUMBER: CIS 210
    COURSE SECTION NUMBER: 01
    INSTRUCTOR NAME: Dr. Tian
    PROJECT NUMBER: 6
    DUE DATE: 9/29/2016
    
SUMMARY
	This program is designed to simulate Stock activity for 30 days
	Program will randomly generate changes (-10% to 10% positive & negative changes)
	Program will ask user to input: stock name, symbol, & current price
	When input is received, program will randomly generate next price of stock for
	the next 29 days (30 days total)
	
	Program will output to user:
	 	1. Stock Name 
	 	2. Stock Symbol  
	 	3. Yesterday's Price**** (user 'currentPrice' input)
	 	4. Today's Price (Randomly generated by Method)
	 	5. Price Movement (Today's Price - Yesterday's Price = +/- change)
	 	6. Change Percent (How to Calculate this?)
	 	
	 	**** = Next Day's (day 2, 3, 4, etc) Price is equal to Yesterday's 'Today Price'
	
INPUT
	Input from user will consist of Strings and Doubles
	Strings: Stock Name & Stock Symbol
	Doubles: Current Stock Price

OUTPUT
	Output from program will be shown on console similar to example format:
	
	STOCK      SYMBOL  YESTERDAY_PRICE 	TODAY_PRICE 	PRICE_MOVEMENT 		CHANGE_PERCENT 
Microsoft     	MSFT        45.65       	47.48           1.83            	4.00% 
 
Microsoft  		MSFT        47.48       	52.22           4.75                10.00% 
 
Microsoft  		MSFT        52.22       	49.61           -2.61               -5.00% 
 


ASSUMPTIONS
- None
*/

import java.util.Scanner;

public class PriceStockSimulation {
	public static void main(String[] args){
		String companyName = new String();		//companyName variable: new String Method
		String companySymbol = new String();	//companySymbol variable: new String Method
		double currentPrice = 0;				//currentPrice set to 0: before user input
		double nextPrice = 0;					//nextPrice set to 0: before user input
		double percentChange = 0;				//percentChange set to 0: before user input
		
		Scanner compNameInput = new Scanner(System.in);
		Scanner compSymbolInput = new Scanner(System.in);
		Scanner currentPriceInput = new Scanner(System.in);
		
		//Creates new Object of Stock for user input (different from default)
		Stock object = new Stock();
		
		//*******************************
		//		START OF PROGRAM		*
		//*******************************
		
		System.out.print("If the user enters NONE, NA, and 0.0 for the name of the company, the symbol, and yesterday's price ");
		System.out.println("respectively, it will use default values.");
		
		System.out.print("Please enter the name of the stock: ");
		companyName = compNameInput.nextLine();
		
		System.out.print("Please enter the symbol of the stock: ");
		companySymbol = compNameInput.nextLine();
		
		System.out.print("Please enter yesterday's price: ");
		currentPrice = currentPriceInput.nextDouble();
		
		object.WhichDefaultValue(companyName, companySymbol, currentPrice);
		
		object.priceChange();
		companyName = object.getName();
		companySymbol = object.getSymbol();
		currentPrice = object.getCurrentPrice();
		nextPrice = object.getNextPrice();
		percentChange = object.getPercentage();
		
		
		for(int i=1; i<=30; i++) {
			
			object.printResults(companyName, companySymbol, currentPrice, nextPrice, percentChange);
			object.setCurrentPrice(nextPrice);
			object.priceChange();
			currentPrice = object.getCurrentPrice();
			nextPrice = object.getNextPrice();
			percentChange = object.getPercentage();
		}//Closes 'for' loop
		
		compNameInput.close();
		compSymbolInput.close();
		currentPriceInput.close();
		
	}//Closes Main Method
}//Closes PriceStockSimulation Class
